### ISSUE TITLE
Stream Listen Not working as expected 

### ISSUE THREAD

**Issue by caryyu** [preservim/nerdcommenter#452]
What i'm trying to do is wanting Kong to act like as the same as Nginx stream config below:

```
stream {
  server {
    listen 7000;
    ssl_preread on;
    resolver 8.8.8.8;
    proxy_pass $ssl_preread_server_name:443;
  }
}
```

# Docker Compose Core Part

```

...

  kong-instance:
    image: kong:2.2.0
    links:
      - kong-database:kong-database
    restart: always
    ports:
      - '8000:8000'
      - '7000:7000'
      - '8443:8443'
      - '8001:8001'
    depends_on:
      - kong-database
    environment:
      - KONG_LUA_PACKAGE_PATH=/opt/?.lua;;
      - KONG_NGINX_DAEMON=off
      - KONG_NGINX_WORKER_PROCESSES=1
      - KONG_PLUGINS=bundled
      - KONG_DATABASE=postgres
      - KONG_PROXY_LISTEN=0.0.0.0:8000,0.0.0.0:8443 ssl
      - KONG_STREAM_LISTEN=0.0.0.0:7000 ssl
      - KONG_NGINX_STREAM_SSL_PREREAD=on
      - KONG_NGINX_STREAM_RESOLVER=8.8.8.8
      - KONG_PG_HOST=kong-database
      - KONG_PG_DATABASE=kong
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kong
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_STREAM_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_STREAM_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_LOG_LEVEL=debug
```

# Test Steps

```
curl -XPOST http://localhost:8001/services -d name=github-proxy -d url=tcp://github.com:443 -d protocol=tcp
curl -XPOST http://localhost:8001/services/github-proxy/routes -d name=github-proxy -d snis=github.com -d protocols=tls
openssl s_client -connect localhost:7000 -servername github.com
```

The output is:

```
...

    Verify return code: 18 (self signed certificate)
---
```

# Expected 

```
$ openssl s_client -connect github.com:443 -servername github.com

...

    Verify return code: 0 (ok)
---
```
